# Generated by Django 5.1.2 on 2024-11-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('acc', models.IntegerField(primary_key='acc', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('pancode', models.IntegerField()),
                ('aadharcode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
